class Main inherits IO {
  s : String <- in_string();
  main() : Object {
    {
      let s2 : String <- s.concat("HELLO WORLD HELLO WORLD HELLO WORLD HELLO WORLD HELLO WORLD HELLO WORLD HELLO WORLD HELLO WORLD HELLO WORLD HELLO WORLD HELLO WORLD HELLO WORLD HELLO WORLD HELLO WORLD HELLO WORLD HELLO WORLD HELLO WORLD HELLO WORLD HELLO WORLD HELLO WORLD HELLWORLD HELLWORLD HELLWORLD HELLWORLD HELLWORLD HELLWORLD HELLWORLD HELLWORLD HELLWORLD HELLWORLD HELLWORLD HELLWORLD HELLWORLD HELLWORLD HELLWORLD HELLWORLD HELLWORLD HELLWORLD HELLWORLD HELLWORLD HELLWORLD HELLWORLD HELLWORLD HELLWORLD HELLWORLD HELLWORLD HELLWORLD HELLOOOOOOOOOOOOOOOOOOOOOOOOOOOOWORLD ") in 
        out_string(s2)
  ;
    }
  } ;
} ;

